import type { Metadata } from "next";
//import { Geist, Geist_Mono, Roboto_Slab } from "next/font/google";
import {Roboto_Slab} from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import "./globals.css";
import { AppSidebar } from "@/app/_component/AppSidebar";


const robotoSlab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} ${robotoSlab.variable} antialiased`}
      >
        <AppSidebar />
        {children}
      </body>
    </html>
  );
}
